spring:
  config:
    activate:
      on-profile: testdb

  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        default_batch_fetch_size: 100
        #format_sql: true
        #show_sql: true

    hibernate:
      ddl-auto: create

# JPA Log
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG