spring:
  config:
    activate:
      on-profile: dev

# Error, Exception
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always

  port: 8080