spring:
  config:
    activate:
      on-profile: linux

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: /Users/junhwan/Desktop/project/temp

path:
  upload: /Users/junhwan/Desktop/project/upload